# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
hydra:
  launcher:
    nodes: 1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: "MEDIUM"
    cpus_per_task: 8
    mem_per_cpu: 8G
    timeout_min: 1200

