# @package _global_
defaults:
  - /paths/home.yaml
  - override /hydra/launcher: submitit_slurm
hydra:
  launcher:
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: "MEDIUM"
    nodes: 1
    cpus_per_task: 8
    mem_per_cpu: 8G
    timeout_min: 1200
