# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
hydra:
  launcher:
    nodes: 1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: "GPU,GPU-DEPINFO"
    gres: "gpu:1"
    cpus_per_task: 2
    mem_per_cpu: 32G
    timeout_min: 1200
    constraint: "[gpu24G]"

